//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERPEntities : DbContext
    {
        public ERPEntities()
            : base("name=ERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<거래처> 거래처 { get; set; }
        public virtual DbSet<검사유형> 검사유형 { get; set; }
        public virtual DbSet<결산자료입력> 결산자료입력 { get; set; }
        public virtual DbSet<계정과목> 계정과목 { get; set; }
        public virtual DbSet<계정과목그룹> 계정과목그룹 { get; set; }
        public virtual DbSet<계정과목등록> 계정과목등록 { get; set; }
        public virtual DbSet<고정자산> 고정자산 { get; set; }
        public virtual DbSet<공급업체> 공급업체 { get; set; }
        public virtual DbSet<공정> 공정 { get; set; }
        public virtual DbSet<공정순서> 공정순서 { get; set; }
        public virtual DbSet<공제별세부사항> 공제별세부사항 { get; set; }
        public virtual DbSet<과세별세액> 과세별세액 { get; set; }
        public virtual DbSet<근로소득별세부사항> 근로소득별세부사항 { get; set; }
        public virtual DbSet<근태결과> 근태결과 { get; set; }
        public virtual DbSet<금융거래처등록> 금융거래처등록 { get; set; }
        public virtual DbSet<급_상여지급_급여구분> 급_상여지급_급여구분 { get; set; }
        public virtual DbSet<급_상여지급_일자등록> 급_상여지급_일자등록 { get; set; }
        public virtual DbSet<급_상여지급_직종및_급여형태> 급_상여지급_직종및_급여형태 { get; set; }
        public virtual DbSet<급여> 급여 { get; set; }
        public virtual DbSet<급여계산> 급여계산 { get; set; }
        public virtual DbSet<급여형태> 급여형태 { get; set; }
        public virtual DbSet<기간비용> 기간비용 { get; set; }
        public virtual DbSet<기간비용계산방법> 기간비용계산방법 { get; set; }
        public virtual DbSet<납품업체> 납품업체 { get; set; }
        public virtual DbSet<메뉴등록> 메뉴등록 { get; set; }
        public virtual DbSet<메뉴별권한설정> 메뉴별권한설정 { get; set; }
        public virtual DbSet<반품처리서> 반품처리서 { get; set; }
        public virtual DbSet<발주리스트> 발주리스트 { get; set; }
        public virtual DbSet<발주서> 발주서 { get; set; }
        public virtual DbSet<발주확인리스트> 발주확인리스트 { get; set; }
        public virtual DbSet<발주확인서> 발주확인서 { get; set; }
        public virtual DbSet<부가세신고서> 부가세신고서 { get; set; }
        public virtual DbSet<부서등록> 부서등록 { get; set; }
        public virtual DbSet<분기별예산> 분기별예산 { get; set; }
        public virtual DbSet<불량상세정보> 불량상세정보 { get; set; }
        public virtual DbSet<불량코드내역> 불량코드내역 { get; set; }
        public virtual DbSet<사업장등록> 사업장등록 { get; set; }
        public virtual DbSet<사용자권한설정> 사용자권한설정 { get; set; }
        public virtual DbSet<사원등록> 사원등록 { get; set; }
        public virtual DbSet<사원상세정보> 사원상세정보 { get; set; }
        public virtual DbSet<생산검사> 생산검사 { get; set; }
        public virtual DbSet<생산계획현황> 생산계획현황 { get; set; }
        public virtual DbSet<생산실적현황> 생산실적현황 { get; set; }
        public virtual DbSet<세금> 세금 { get; set; }
        public virtual DbSet<세무유형> 세무유형 { get; set; }
        public virtual DbSet<소득_세액공제환경설정> 소득_세액공제환경설정 { get; set; }
        public virtual DbSet<소요량전개> 소요량전개 { get; set; }
        public virtual DbSet<수주> 수주 { get; set; }
        public virtual DbSet<수주확인리스트> 수주확인리스트 { get; set; }
        public virtual DbSet<수주확인서> 수주확인서 { get; set; }
        public virtual DbSet<시스템환경설정> 시스템환경설정 { get; set; }
        public virtual DbSet<업무용승용차_차량등록> 업무용승용차_차량등록 { get; set; }
        public virtual DbSet<역추적> 역추적 { get; set; }
        public virtual DbSet<예산> 예산 { get; set; }
        public virtual DbSet<일반거래처등록> 일반거래처등록 { get; set; }
        public virtual DbSet<입고검사> 입고검사 { get; set; }
        public virtual DbSet<자금계획달력> 자금계획달력 { get; set; }
        public virtual DbSet<자금과목> 자금과목 { get; set; }
        public virtual DbSet<자재> 자재 { get; set; }
        public virtual DbSet<자재명세서> 자재명세서 { get; set; }
        public virtual DbSet<자재전표> 자재전표 { get; set; }
        public virtual DbSet<작업완료지시> 작업완료지시 { get; set; }
        public virtual DbSet<작업완료확인서> 작업완료확인서 { get; set; }
        public virtual DbSet<작업지시> 작업지시 { get; set; }
        public virtual DbSet<작업지시리스트> 작업지시리스트 { get; set; }
        public virtual DbSet<작업지시현황> 작업지시현황 { get; set; }
        public virtual DbSet<전표> 전표 { get; set; }
        public virtual DbSet<전표리스트> 전표리스트 { get; set; }
        public virtual DbSet<제품> 제품 { get; set; }
        public virtual DbSet<퇴직공제항목> 퇴직공제항목 { get; set; }
        public virtual DbSet<퇴직금> 퇴직금 { get; set; }
        public virtual DbSet<퇴직기준설정> 퇴직기준설정 { get; set; }
        public virtual DbSet<퇴직지급항목> 퇴직지급항목 { get; set; }
        public virtual DbSet<투입현황1> 투입현황1 { get; set; }
        public virtual DbSet<품목정보> 품목정보 { get; set; }
        public virtual DbSet<프로젝트등록> 프로젝트등록 { get; set; }
        public virtual DbSet<회사등록> 회사등록 { get; set; }
    }
}
