//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 거래처
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 거래처()
        {
            this.거래처구분 = new HashSet<거래처구분>();
            this.자금계획달력 = new HashSet<자금계획달력>();
            this.전표리스트 = new HashSet<전표리스트>();
        }
    
        public int 거래처코드번호 { get; set; }
        public string 거래처명 { get; set; }
        public int 거래처구분ID { get; set; }
        public string 사업자등록번호 { get; set; }
        public string 대표자성명 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<거래처구분> 거래처구분 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<자금계획달력> 자금계획달력 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<전표리스트> 전표리스트 { get; set; }
    }
}
