//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 거래처구분
    {
        public int 거래처구분ID { get; set; }
        public string 구분명 { get; set; }
        public int 거래처코드번호 { get; set; }
    
        public virtual 거래처 거래처 { get; set; }
    }
}
