//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 결산자료입력
    {
        public int 결산자료코드 { get; set; }
        public string 결산자료구분 { get; set; }
        public string 결산계정코드 { get; set; }
        public string 결산계정적요 { get; set; }
        public string 결산계정명 { get; set; }
        public string 상대계정코드 { get; set; }
        public string 상대계정적요 { get; set; }
        public string 상대계정명 { get; set; }
        public string 비고 { get; set; }
    }
}
