//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 계정과목
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 계정과목()
        {
            this.고정자산 = new HashSet<고정자산>();
            this.전표리스트 = new HashSet<전표리스트>();
        }
    
        public int 계정과목코드번호 { get; set; }
        public string 계정과목명 { get; set; }
        public string 출력계정명 { get; set; }
        public string 계정구분 { get; set; }
        public string 차대구분 { get; set; }
        public string 입력구분 { get; set; }
        public string 필수입력여부 { get; set; }
        public string 비고 { get; set; }
        public int 그룹코드번호 { get; set; }
    
        public virtual 계정과목그룹 계정과목그룹 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<고정자산> 고정자산 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<전표리스트> 전표리스트 { get; set; }
    }
}
