//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 고정자산
    {
        public int 고정자산코드 { get; set; }
        public string 고정자산명 { get; set; }
        public System.DateTime 취득일 { get; set; }
        public string 처리여부 { get; set; }
        public int 취득원가 { get; set; }
        public int 전기말상각누계액 { get; set; }
        public int 상각방법코드번호 { get; set; }
        public int 내용연수 { get; set; }
        public int 일반상각비 { get; set; }
        public int 취득수량 { get; set; }
        public int 경비구분코드번호 { get; set; }
    
        public virtual 경비구분 경비구분 { get; set; }
        public virtual 상각방법 상각방법 { get; set; }
    }
}
