//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 고정자산
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 고정자산()
        {
            this.업무용승용차_차량등록 = new HashSet<업무용승용차_차량등록>();
        }
    
        public int 고정자산코드 { get; set; }
        public string 고정자산명 { get; set; }
        public System.DateTime 취득일 { get; set; }
        public string 처리여부 { get; set; }
        public int 취득원가 { get; set; }
        public int 전기말상각누계액 { get; set; }
        public string 상각방법 { get; set; }
        public int 내용연수 { get; set; }
        public string 경비구분 { get; set; }
        public int 취득수량 { get; set; }
        public int 일반상각비 { get; set; }
        public int 당기말상각누계액 { get; set; }
        public System.DateTime 입력일자 { get; set; }
        public System.DateTime 수정일자 { get; set; }
        public string 구입처 { get; set; }
        public string 제작사 { get; set; }
        public Nullable<decimal> 규격 { get; set; }
        public string 모델 { get; set; }
        public string 사원코드 { get; set; }
        public string 비고 { get; set; }
        public int 계정과목코드번호 { get; set; }
    
        public virtual 계정과목 계정과목 { get; set; }
        public virtual 사원등록 사원등록 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<업무용승용차_차량등록> 업무용승용차_차량등록 { get; set; }
    }
}
