//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 공제별세부사항
    {
        public int 공제별세부사항번호 { get; set; }
        public string 항목명 { get; set; }
        public float 공제율 { get; set; }
        public int 공제액 { get; set; }
        public string 비과세구분 { get; set; }
        public string 비과세코드 { get; set; }
        public string 항목 { get; set; }
        public bool 지급명세서_작성 { get; set; }
        public int 항목ID { get; set; }
    
        public virtual 근로소득 근로소득 { get; set; }
    }
}
