//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 공제별세부사항
    {
        public string 공제별세부사항코드 { get; set; }
        public int 번호 { get; set; }
        public string 항목명 { get; set; }
        public decimal 공제율 { get; set; }
        public int 공제액 { get; set; }
        public string 항목 { get; set; }
        public string 지급명세서_작성 { get; set; }
        public System.DateTime 귀속연도 { get; set; }
    
        public virtual 소득_세액공제환경설정 소득_세액공제환경설정 { get; set; }
    }
}
