//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 과세별세액
    {
        public int 일반과세ID { get; set; }
        public string 구분 { get; set; }
        public int 금액 { get; set; }
        public int 세액 { get; set; }
        public int 역추적ID { get; set; }
        public System.DateTime 회계기간 { get; set; }
    
        public virtual 부가세신고서 부가세신고서 { get; set; }
    }
}
