//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 근로소득
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 근로소득()
        {
            this.공제별세부사항 = new HashSet<공제별세부사항>();
            this.근로소득별세부사항 = new HashSet<근로소득별세부사항>();
        }
    
        public int 항목ID { get; set; }
        public string 항목명 { get; set; }
        public System.DateTime 귀속연도 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<공제별세부사항> 공제별세부사항 { get; set; }
        public virtual 소득_세액공제환경설정 소득_세액공제환경설정 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<근로소득별세부사항> 근로소득별세부사항 { get; set; }
    }
}
