//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 급_상여지급_급여구분
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 급_상여지급_급여구분()
        {
            this.급_상여지급_직종및_급여형태 = new HashSet<급_상여지급_직종및_급여형태>();
        }
    
        public int 지급번호코드 { get; set; }
        public bool 급여구분 { get; set; }
        public string 입사자상여계산_방법 { get; set; }
        public string 입사자상여계산_기준일_수 { get; set; }
        public string 퇴사자상여계산_방법 { get; set; }
        public string 퇴사자상여계산_기준일_수 { get; set; }
        public System.DateTime 귀속연월 { get; set; }
    
        public virtual 급_상여지급_일자등록 급_상여지급_일자등록 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<급_상여지급_직종및_급여형태> 급_상여지급_직종및_급여형태 { get; set; }
    }
}
