//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 급_상여지급_일자등록
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 급_상여지급_일자등록()
        {
            this.급_상여지급_급여구분 = new HashSet<급_상여지급_급여구분>();
        }
    
        public System.DateTime 귀속연월 { get; set; }
        public int 지급순번코드 { get; set; }
        public System.DateTime 지급일자 { get; set; }
        public bool 동시발행 { get; set; }
        public bool 대상자선정 { get; set; }
        public string 비고 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<급_상여지급_급여구분> 급_상여지급_급여구분 { get; set; }
    }
}
