//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 급_상여지급_일자등록
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 급_상여지급_일자등록()
        {
            this.급_상여지급_급여구분 = new HashSet<급_상여지급_급여구분>();
        }
    
        public System.DateTime 귀속연월 { get; set; }
        public int 지급순번코드 { get; set; }
        public System.DateTime 지급일자 { get; set; }
        public bool 동시발행 { get; set; }
        public bool 대상자선정 { get; set; }
        public string 비고 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<급_상여지급_급여구분> 급_상여지급_급여구분 { get; set; }
    }
}
