//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 급여
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 급여()
        {
            this.세금 = new HashSet<세금>();
        }
    
        public int 급여지급번호 { get; set; }
        public int 기본급 { get; set; }
        public Nullable<int> 상여금 { get; set; }
        public int 연장근로수당 { get; set; }
        public int 자격수당 { get; set; }
        public System.DateTime 귀속연월 { get; set; }
        public System.DateTime 급여지급일 { get; set; }
        public int 실수령액 { get; set; }
    
        public virtual 급여계산 급여계산 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<세금> 세금 { get; set; }
    }
}
