//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 급여정보
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 급여정보()
        {
            this.사원정보 = new HashSet<사원정보>();
        }
    
        public int 급여정보코드번호 { get; set; }
        public string 호봉 { get; set; }
        public string 계정유형 { get; set; }
        public string 생산직총급여 { get; set; }
        public bool 파견근로자여부 { get; set; }
        public string 호봉당급여금액 { get; set; }
        public string 호봉종류 { get; set; }
        public string 예금주명 { get; set; }
        public string 은행명 { get; set; }
        public string 계좌번호 { get; set; }
        public int 국민연금 { get; set; }
        public int 고용보험 { get; set; }
        public int 건강보험 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<사원정보> 사원정보 { get; set; }
    }
}
