//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 급여지급대상
    {
        public int 급여지급대상번호 { get; set; }
        public int 사원코드 { get; set; }
        public string 지급항목명 { get; set; }
        public int 지급금액 { get; set; }
        public string 공제항목명 { get; set; }
        public int 공제금액 { get; set; }
        public System.DateTime 귀속연월 { get; set; }
        public System.DateTime 급여지급일 { get; set; }
    
        public virtual 급여입력및계산 급여입력및계산 { get; set; }
    }
}
