//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 기준설정
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 기준설정()
        {
            this.환경요소 = new HashSet<환경요소>();
        }
    
        public int 기준설정ID { get; set; }
        public string 구분 { get; set; }
        public int 번호 { get; set; }
    
        public virtual 인사_급여환경설정 인사_급여환경설정 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<환경요소> 환경요소 { get; set; }
    }
}
