//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 메뉴별권한설정
    {
        public int 메뉴별권한설정코드 { get; set; }
        public string 조회권한 { get; set; }
        public bool 변경 { get; set; }
        public bool 삭제 { get; set; }
        public bool 출력 { get; set; }
        public string 메뉴명 { get; set; }
    
        public virtual 사용자권한설정 사용자권한설정 { get; set; }
    }
}
