//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 메뉴등록
    {
        public string CodeNum { get; set; }
        public string Title { get; set; }
        public string PrentKey { get; set; }
        public string ControlName { get; set; }
    }
}
