//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 반품처리서
    {
        public int 반품처리서번호 { get; set; }
        public int 공급업체번호 { get; set; }
        public int 입고검사서번호 { get; set; }
    
        public virtual 공급업체 공급업체 { get; set; }
        public virtual 입고검사서 입고검사서 { get; set; }
    }
}
