//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 발주확인리스트
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 발주확인리스트()
        {
            this.입고검사 = new HashSet<입고검사>();
        }
    
        public int 발주확인서번호 { get; set; }
        public int 자재번호 { get; set; }
        public int 수량 { get; set; }
    
        public virtual 발주확인서 발주확인서 { get; set; }
        public virtual 자재 자재 { get; set; }
        public virtual 자재전표 자재전표 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<입고검사> 입고검사 { get; set; }
    }
}
