//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 발주리스트
    {
        public int 자재번호 { get; set; }
        public int 발주번호 { get; set; }
        public int 수량 { get; set; }
    
        public virtual 발주서 발주서 { get; set; }
        public virtual 자재 자재 { get; set; }
    }
}
