//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 부서등록
    {
        public string 부서코드 { get; set; }
        public string 부서명 { get; set; }
        public string 사업장코드 { get; set; }
        public int 부문코드 { get; set; }
        public string 부문명 { get; set; }
        public System.DateTime 사용시작기간 { get; set; }
        public Nullable<System.DateTime> 사용종료기간 { get; set; }
        public string 사원코드 { get; set; }
    
        public virtual 사업장등록 사업장등록 { get; set; }
        public virtual 사원등록 사원등록 { get; set; }
    }
}
