//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 부서등록
    {
        public int 부서코드 { get; set; }
        public string 부서명 { get; set; }
        public int 사업장코드 { get; set; }
        public string 사업장명 { get; set; }
        public int 부문코드 { get; set; }
        public string 부문명 { get; set; }
        public System.DateTime 사용기간 { get; set; }
        public string 사원코드 { get; set; }
    
        public virtual 사원등록 사원등록 { get; set; }
    }
}
