//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 분기별예산
    {
        public int 월별예산코드 { get; set; }
        public int C1월_금액 { get; set; }
        public int C2월_금액 { get; set; }
        public int C3월_금액 { get; set; }
        public int C4월_금액 { get; set; }
        public int C5월_금액 { get; set; }
        public int C6월_금액 { get; set; }
        public int C7월_금액 { get; set; }
        public int C8월_금액 { get; set; }
        public int C9월_금액 { get; set; }
        public int C10월_금액 { get; set; }
        public int C11월_금액 { get; set; }
        public int C12월_금액 { get; set; }
        public int 예산코드 { get; set; }
        public System.DateTime 신청연도 { get; set; }
    
        public virtual 예산 예산 { get; set; }
    }
}
