//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 분기별예산
    {
        public int 월별예산코드 { get; set; }
        public int C1월_금액 { get; set; }
        public int C2월_금액 { get; set; }
        public int C3월_금액 { get; set; }
        public int C4월_금액 { get; set; }
        public int C5월_금액 { get; set; }
        public int C6월_금액 { get; set; }
        public int C7월_금액 { get; set; }
        public int C8월_금액 { get; set; }
        public int C9월_금액 { get; set; }
        public int C10월_금액 { get; set; }
        public int C11월_금액 { get; set; }
        public int C12월_금액 { get; set; }
        public int 예산코드 { get; set; }
        public System.DateTime 신청연도 { get; set; }
    
        public virtual 예산 예산 { get; set; }
    }
}
