//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 불량상세정보
    {
        public int 불량코드번호 { get; set; }
        public int 입고검사서번호 { get; set; }
        public Nullable<int> 불량수량 { get; set; }
    
        public virtual 불량코드내역 불량코드내역 { get; set; }
        public virtual 입고검사서 입고검사서 { get; set; }
    }
}
