//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 사업장관할세무서
    {
        public int 관할세무서코드번호 { get; set; }
        public string 관할세무서명 { get; set; }
        public int 사업장등록번호 { get; set; }
    
        public virtual 사업장기본등록사항 사업장기본등록사항 { get; set; }
    }
}
