//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 사원인적정보
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 사원인적정보()
        {
            this.사용자권한설정 = new HashSet<사용자권한설정>();
        }
    
        public string 사원코드 { get; set; }
        public byte[] 사원사진 { get; set; }
        public string 사원이름_영문_ { get; set; }
        public bool 내외국인구분 { get; set; }
        public string 주민등록번호 { get; set; }
        public bool 성별 { get; set; }
        public System.DateTime 생년월일 { get; set; }
        public string 전화번호 { get; set; }
        public string 비상연락_HP_ { get; set; }
        public string 최종학력 { get; set; }
        public string 주민등록주소 { get; set; }
        public string 상세주소 { get; set; }
        public string E_MAIL { get; set; }
        public int 인사정보등록번호 { get; set; }
        public System.DateTime 입사일 { get; set; }
        public System.DateTime 퇴직일 { get; set; }
        public System.DateTime 중도퇴사일 { get; set; }
        public string 재직구분 { get; set; }
        public System.DateTime 퇴직연금가입일 { get; set; }
        public string 부서 { get; set; }
        public string 고용형태 { get; set; }
        public string 직종 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<사용자권한설정> 사용자권한설정 { get; set; }
        public virtual 사원등록 사원등록 { get; set; }
    }
}
