//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 사업장등록
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 사업장등록()
        {
            this.부서등록 = new HashSet<부서등록>();
        }
    
        public string 사업장코드 { get; set; }
        public string 사업장명 { get; set; }
        public string 사업장등록번호 { get; set; }
        public string 대표자명 { get; set; }
        public string 사업장주소 { get; set; }
        public string 사업장번지 { get; set; }
        public string 사업장전화번호 { get; set; }
        public string 업태 { get; set; }
        public string 종목 { get; set; }
        public string 관할세무서 { get; set; }
        public System.DateTime 개업년월일 { get; set; }
        public Nullable<System.DateTime> 폐업년월일 { get; set; }
        public System.DateTime 회계기간 { get; set; }
    
        public virtual 부가세신고서 부가세신고서 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<부서등록> 부서등록 { get; set; }
    }
}
