//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 사원정보
    {
        public int 인사정보등록번호 { get; set; }
        public int 사원코드 { get; set; }
        public int 급여정보코드번호 { get; set; }
    
        public virtual 급여정보 급여정보 { get; set; }
        public virtual 사원정보등록 사원정보등록 { get; set; }
    }
}
