//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 사용자권한설정
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 사용자권한설정()
        {
            this.메뉴별권한설정 = new HashSet<메뉴별권한설정>();
        }
    
        public string 메뉴명 { get; set; }
        public bool 선택여부 { get; set; }
        public string 사원코드 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<메뉴별권한설정> 메뉴별권한설정 { get; set; }
        public virtual 사원인적정보 사원인적정보 { get; set; }
    }
}
