//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 수주확인서
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 수주확인서()
        {
            this.수주확인리스트 = new HashSet<수주확인리스트>();
        }
    
        public int 수주확인번호 { get; set; }
        public System.DateTime 배달날짜 { get; set; }
        public int 납품업체번호 { get; set; }
    
        public virtual 납품업체 납품업체 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<수주확인리스트> 수주확인리스트 { get; set; }
    }
}
