//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 수주
    {
        public string 수주번호 { get; set; }
        public string 수주번호2 { get; set; }
        public int 제품번호 { get; set; }
        public int 주문수량 { get; set; }
        public int 납품업체번호 { get; set; }
        public Nullable<int> 주문일 { get; set; }
        public Nullable<int> 납기일 { get; set; }
    
        public virtual 납품업체 납품업체 { get; set; }
        public virtual 제품 제품 { get; set; }
    }
}
