//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 시스템환경설정
    {
        public string 구분 { get; set; }
        public string 환경요소명 { get; set; }
        public string 유형구분 { get; set; }
        public int 유형설정 { get; set; }
        public string 선택범위 { get; set; }
        public string 비고 { get; set; }
    }
}
