//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 시스템환경설정
    {
        public int 시스템환경설정코드 { get; set; }
        public string 구분 { get; set; }
        public string 환경요소명 { get; set; }
        public string 유형구분 { get; set; }
        public int 유형설정 { get; set; }
        public string 선택범위 { get; set; }
        public string 비고 { get; set; }
    }
}
