//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 업무용승용차_차량등록
    {
        public int 업무용승용차코드번호 { get; set; }
        public string 차량번호 { get; set; }
        public string 차종 { get; set; }
        public string 경비구분 { get; set; }
        public bool 보험여부 { get; set; }
        public System.DateTime 취득일자 { get; set; }
        public System.DateTime 처분일자 { get; set; }
        public bool 사용여부 { get; set; }
        public string 임차구분 { get; set; }
        public System.DateTime 임차기간시작일 { get; set; }
        public System.DateTime 임차기간종료일 { get; set; }
        public bool 사용구분 { get; set; }
    }
}
