//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 역추적
    {
        public int 역추적ID { get; set; }
        public int 번호 { get; set; }
        public string 세무유형 { get; set; }
        public int 공급가액 { get; set; }
        public int 부가세 { get; set; }
    
        public virtual 세무유형 세무유형1 { get; set; }
    }
}
