//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 역추적
    {
        public int 역추적ID { get; set; }
        public int 번호 { get; set; }
        public string 세무유형 { get; set; }
        public int 공급가액 { get; set; }
        public int 부가세 { get; set; }
    
        public virtual 세무유형 세무유형1 { get; set; }
    }
}
