//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 일반거래처등록
    {
        public string 일반거래처코드 { get; set; }
        public string 거래처코드번호 { get; set; }
        public string 거래처명 { get; set; }
        public string 구분 { get; set; }
        public string 사업자등록번호 { get; set; }
        public string 주민등록번호 { get; set; }
        public string 대표자성명 { get; set; }
        public string 업태 { get; set; }
        public string 종목 { get; set; }
        public string 사업장주소 { get; set; }
        public string 사업장번지 { get; set; }
        public string 사업장전화번호 { get; set; }
        public System.DateTime 거래시작일 { get; set; }
        public System.DateTime 거래종료일 { get; set; }
        public Nullable<System.DateTime> 계약거래시작일 { get; set; }
        public Nullable<System.DateTime> 계약거래종료일 { get; set; }
        public string 계약거래형태 { get; set; }
        public int 게약거래금액 { get; set; }
        public string 매입거래금융기관 { get; set; }
        public string 매입거래처 { get; set; }
        public string 매입거래예금주 { get; set; }
        public string 매입거래계좌번호 { get; set; }
        public string 매출거래은행코드 { get; set; }
        public string 매출거래처 { get; set; }
        public string 매출거래계좌번호 { get; set; }
        public Nullable<System.DateTime> 자금결제및수금관리예정일 { get; set; }
    
        public virtual 거래처 거래처 { get; set; }
    }
}
