//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 자금계획달력
    {
        public System.DateTime 일자 { get; set; }
        public int 자금과목코드번호 { get; set; }
        public int 거래처코드번호 { get; set; }
        public string 적요 { get; set; }
        public int 금액 { get; set; }
        public int 잔액 { get; set; }
    
        public virtual 거래처 거래처 { get; set; }
        public virtual 자금과목 자금과목 { get; set; }
    }
}
