//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 작업완료확인서
    {
        public int 작업완료지시번호 { get; set; }
        public int 제품번호 { get; set; }
        public System.DateTime 작업완료일 { get; set; }
        public int 수량 { get; set; }
        public int 생산실적검사여부 { get; set; }
        public int 입고여부 { get; set; }
    
        public virtual 제품 제품 { get; set; }
    }
}
