//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 작업지시현황
    {
        public int 작업지시번호 { get; set; }
        public int 생산계획현황번호 { get; set; }
        public int 제품번호 { get; set; }
        public string 수량 { get; set; }
        public string 작업장번호 { get; set; }
        public string 작업상태번호 { get; set; }
        public string 작업지시일 { get; set; }
        public string 작업완료_예정_일 { get; set; }
        public int 자재명세번호 { get; set; }
        public int 공정번호 { get; set; }
    
        public virtual 공정 공정 { get; set; }
        public virtual 생산계획현황 생산계획현황 { get; set; }
    }
}
