//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 전표
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 전표()
        {
            this.전표리스트 = new HashSet<전표리스트>();
        }
    
        public System.DateTime 입력날짜 { get; set; }
        public int 전표번호 { get; set; }
        public string 품의내역 { get; set; }
        public string 유형 { get; set; }
        public string 기표번호 { get; set; }
        public bool 승인상태 { get; set; }
        public string 승인자 { get; set; }
        public int 대차차액 { get; set; }
        public string 작업자 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<전표리스트> 전표리스트 { get; set; }
    }
}
