//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 전표리스트
    {
        public int 전표리스트ID { get; set; }
        public int 순번 { get; set; }
        public bool 차변대변구분 { get; set; }
        public int 계정과목코드번호 { get; set; }
        public int 거래처코드번호 { get; set; }
        public string 사업자_주민_번호 { get; set; }
        public int 금액 { get; set; }
        public int 적요번호 { get; set; }
        public string 적요명 { get; set; }
        public System.DateTime 입력날짜 { get; set; }
        public int 전표번호 { get; set; }
    
        public virtual 거래처 거래처 { get; set; }
        public virtual 계정과목 계정과목 { get; set; }
        public virtual 전표 전표 { get; set; }
    }
}
