//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 전표
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 전표()
        {
            this.전표리스트 = new HashSet<전표리스트>();
        }
    
        public System.DateTime 입력날짜 { get; set; }
        public int 전표번호 { get; set; }
        public string 품의내역 { get; set; }
        public string 유형 { get; set; }
        public string 기표번호 { get; set; }
        public string 승인상태 { get; set; }
        public string 승인자 { get; set; }
        public Nullable<int> 대차차액 { get; set; }
        public string 작업자 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<전표리스트> 전표리스트 { get; set; }
    }
}
