//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 코드
    {
        public string 코드1 { get; set; }
        public string 명칭 { get; set; }
        public int 코드분류ID { get; set; }
    
        public virtual 코드분류 코드분류 { get; set; }
    }
}
