//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 퇴직기준설명
    {
        public string 구분 { get; set; }
        public string 항목 { get; set; }
        public string 설정 { get; set; }
        public string 설명 { get; set; }
    }
}
