//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 퇴직지급항목
    {
        public int 지급항목코드 { get; set; }
        public string 퇴직소득유형 { get; set; }
        public string 항목명 { get; set; }
    }
}
