//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 투입현황1
    {
        public string 관리번호 { get; set; }
        public string 품목번호 { get; set; }
        public bool 자재불출 { get; set; }
        public int 투입수량 { get; set; }
        public System.DateTime 투입일 { get; set; }
    }
}
