//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 품목정보
    {
        public string 품목번호 { get; set; }
        public string 전공정 { get; set; }
        public string 후공정 { get; set; }
        public string 외경 { get; set; }
        public string 색상 { get; set; }
        public string 층 { get; set; }
        public string 최종공정 { get; set; }
    }
}
