//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 프로젝트등록
    {
        public string 프로젝트코드 { get; set; }
        public string 프로젝트명 { get; set; }
        public string 구분 { get; set; }
        public System.DateTime 프로젝트시작일 { get; set; }
        public System.DateTime 프로젝트종료일 { get; set; }
        public string 원청회사 { get; set; }
        public System.DateTime 시작일 { get; set; }
        public decimal 프로젝트금액 { get; set; }
        public string 책임자 { get; set; }
        public string 근무지 { get; set; }
    }
}
