//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 환경요소
    {
        public int 환경요소ID { get; set; }
        public string 환경요소명 { get; set; }
        public string 기준 { get; set; }
        public System.DateTime 기준일_월_수 { get; set; }
        public int 기준설정ID { get; set; }
    
        public virtual 기준설정 기준설정 { get; set; }
    }
}
