//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 회사등록
    {
        public string 회사코드 { get; set; }
        public string 회사명 { get; set; }
        public string 사업자등록번호 { get; set; }
        public System.DateTime 회계년도시작일 { get; set; }
        public System.DateTime 회계년도종료일 { get; set; }
        public string 대표자_성명 { get; set; }
        public string 주민등록번호 { get; set; }
        public string 본점_주소 { get; set; }
        public string 본점_번지 { get; set; }
        public string 본점_전화번호 { get; set; }
        public string 업태 { get; set; }
        public string 종목 { get; set; }
        public System.DateTime 설립연월일 { get; set; }
        public System.DateTime 개업연월일 { get; set; }
        public Nullable<System.DateTime> 폐업연월일 { get; set; }
    }
}
