//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class 회사기본등록사항
    {
        public string 사업자등록번호 { get; set; }
        public System.DateTime 회계년도 { get; set; }
        public string 법인등록번호 { get; set; }
        public string 대표자_성명 { get; set; }
        public string 주민등록번호 { get; set; }
        public string 본점_우편번호 { get; set; }
        public string 본점_주소 { get; set; }
        public string 본점_번지 { get; set; }
        public string 본점_전화번호 { get; set; }
        public string 본점_FAX { get; set; }
        public string 업태 { get; set; }
        public string 종목 { get; set; }
        public System.DateTime 설립연월일 { get; set; }
        public System.DateTime 개업연월일 { get; set; }
        public Nullable<System.DateTime> 폐업연월일 { get; set; }
        public int 회사등록코드번호 { get; set; }
    
        public virtual 회사등록 회사등록 { get; set; }
    }
}
